s1 = int(input("Enter the marks of s1 : "))
s2 = int(input("Enter the marks of s2 : "))
s3 = int(input("Enter the marks of s3 : "))
s4 = int(input("Enter the marks of s4 : "))
s5 = int(input("Enter the marks of s5 : "))
s6 = int(input("Enter the marks of s6 : "))
marks = [s1,s2,s3,s4,s5,s6]
print("Unsorted : ",marks)
marks.sort()
print("Sort : ",marks)